/* md5-compare.h generated by valac 0.56.17, the Vala compiler, do not modify */

#ifndef __MD5_COMPARE_H__
#define __MD5_COMPARE_H__

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define FILE_INTEGRITY_CHECKER_TYPE_FILE_COMPARATOR (file_integrity_checker_file_comparator_get_type ())
#define FILE_INTEGRITY_CHECKER_FILE_COMPARATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILE_INTEGRITY_CHECKER_TYPE_FILE_COMPARATOR, FileIntegrityCheckerFileComparator))
#define FILE_INTEGRITY_CHECKER_FILE_COMPARATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILE_INTEGRITY_CHECKER_TYPE_FILE_COMPARATOR, FileIntegrityCheckerFileComparatorClass))
#define FILE_INTEGRITY_CHECKER_IS_FILE_COMPARATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILE_INTEGRITY_CHECKER_TYPE_FILE_COMPARATOR))
#define FILE_INTEGRITY_CHECKER_IS_FILE_COMPARATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILE_INTEGRITY_CHECKER_TYPE_FILE_COMPARATOR))
#define FILE_INTEGRITY_CHECKER_FILE_COMPARATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILE_INTEGRITY_CHECKER_TYPE_FILE_COMPARATOR, FileIntegrityCheckerFileComparatorClass))

typedef struct _FileIntegrityCheckerFileComparator FileIntegrityCheckerFileComparator;
typedef struct _FileIntegrityCheckerFileComparatorClass FileIntegrityCheckerFileComparatorClass;
typedef struct _FileIntegrityCheckerFileComparatorPrivate FileIntegrityCheckerFileComparatorPrivate;

#define FILE_INTEGRITY_CHECKER_TYPE_FILE_UTILS (file_integrity_checker_file_utils_get_type ())
#define FILE_INTEGRITY_CHECKER_FILE_UTILS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILE_INTEGRITY_CHECKER_TYPE_FILE_UTILS, FileIntegrityCheckerFileUtils))
#define FILE_INTEGRITY_CHECKER_FILE_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILE_INTEGRITY_CHECKER_TYPE_FILE_UTILS, FileIntegrityCheckerFileUtilsClass))
#define FILE_INTEGRITY_CHECKER_IS_FILE_UTILS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILE_INTEGRITY_CHECKER_TYPE_FILE_UTILS))
#define FILE_INTEGRITY_CHECKER_IS_FILE_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILE_INTEGRITY_CHECKER_TYPE_FILE_UTILS))
#define FILE_INTEGRITY_CHECKER_FILE_UTILS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILE_INTEGRITY_CHECKER_TYPE_FILE_UTILS, FileIntegrityCheckerFileUtilsClass))

typedef struct _FileIntegrityCheckerFileUtils FileIntegrityCheckerFileUtils;
typedef struct _FileIntegrityCheckerFileUtilsClass FileIntegrityCheckerFileUtilsClass;
typedef struct _FileIntegrityCheckerFileUtilsPrivate FileIntegrityCheckerFileUtilsPrivate;

struct _FileIntegrityCheckerFileComparator {
	GObject parent_instance;
	FileIntegrityCheckerFileComparatorPrivate * priv;
	gchar* directory1;
	gchar* directory2;
	GList* dir1_files_list;
	GList* dir2_files_list;
	GList* dir_compare_int_result;
};

struct _FileIntegrityCheckerFileComparatorClass {
	GObjectClass parent_class;
};

struct _FileIntegrityCheckerFileUtils {
	GObject parent_instance;
	FileIntegrityCheckerFileUtilsPrivate * priv;
	GList* error_lines;
};

struct _FileIntegrityCheckerFileUtilsClass {
	GObjectClass parent_class;
};

VALA_EXTERN GType file_integrity_checker_file_comparator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FileIntegrityCheckerFileComparator, g_object_unref)
VALA_EXTERN FileIntegrityCheckerFileComparator* file_integrity_checker_file_comparator_new (const gchar* dir1,
                                                                                const gchar* dir2);
VALA_EXTERN FileIntegrityCheckerFileComparator* file_integrity_checker_file_comparator_construct (GType object_type,
                                                                                      const gchar* dir1,
                                                                                      const gchar* dir2);
VALA_EXTERN void file_integrity_checker_file_comparator_compare_directories (FileIntegrityCheckerFileComparator* self);
VALA_EXTERN void file_integrity_checker_file_comparator_traverse_directory (FileIntegrityCheckerFileComparator* self,
                                                                const gchar* path,
                                                                gint num);
VALA_EXTERN gboolean file_integrity_checker_file_comparator_check_file_integrity (FileIntegrityCheckerFileComparator* self,
                                                                      const gchar* file1,
                                                                      const gchar* file2);
VALA_EXTERN void file_integrity_checker_file_comparator_generate_report (FileIntegrityCheckerFileComparator* self);
VALA_EXTERN GType file_integrity_checker_file_utils_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FileIntegrityCheckerFileUtils, g_object_unref)
VALA_EXTERN gchar* file_integrity_checker_file_utils_calculate_checksum (const gchar* file_path);
VALA_EXTERN gchar* file_integrity_checker_file_utils_compare_files_lines (FileIntegrityCheckerFileUtils* self,
                                                              const gchar* file1_path,
                                                              const gchar* file2_path);
VALA_EXTERN FileIntegrityCheckerFileUtils* file_integrity_checker_file_utils_new (void);
VALA_EXTERN FileIntegrityCheckerFileUtils* file_integrity_checker_file_utils_construct (GType object_type);

G_END_DECLS

#endif
